'use strict';
const $=id=>document.getElementById(id),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const host=location.hostname.split('.'),parts=location.pathname.split('/').filter(Boolean);const autoOwner=host.length>=3&&host.slice(-2).join('.')==='github.io'?host[0]:'';const autoRepo=host.length>=3&&host.slice(-2).join('.')==='github.io'?(parts[0]&&parts[0]!=='admin'?parts[0]:autoOwner+'.github.io'):'';$('owner').value=autoOwner;$('repo').value=autoRepo;
let token=sessionStorage.getItem('mangaatlas_token')||'',owner='',repo='',branch='main',db=null,editMangaId=null,editChapterId=null;
function msg(t,login=false){$(login?'loginStatus':'status').textContent=t}function ghHeaders(json=false){const h={Authorization:'Bearer '+token,Accept:'application/vnd.github+json'};if(json)h['Content-Type']='application/json';return h}
async function gh(path,opts={},tries=0){const r=await fetch('https://api.github.com/repos/'+encodeURIComponent(owner)+'/'+encodeURIComponent(repo)+path,{...opts,headers:{...ghHeaders(!!opts.body),...(opts.headers||{})},cache:'no-store'});const text=await r.text();if((r.status===409||r.status===429||r.status>=500)&&tries<4){await sleep(800*(tries+1));return gh(path,opts,tries+1)}if(!r.ok)throw Error('GitHub '+r.status+': '+text.slice(0,600));return text?JSON.parse(text):{}}
function b64(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
async function readDb(){const x=await gh('/contents/data/content.json?ref='+branch);const raw=atob(x.content.replace(/\n/g,''));return{data:JSON.parse(new TextDecoder().decode(Uint8Array.from(raw,c=>c.charCodeAt(0)))),sha:x.sha}}
async function writeDb(data,sha,message){const bytes=new TextEncoder().encode(JSON.stringify(data,null,2)+'\n');return gh('/contents/data/content.json',{method:'PUT',body:JSON.stringify({message,content:b64(bytes),sha,branch})})}
function slugify(s){return String(s||'').trim().toLowerCase().normalize('NFKD').replace(/[^\w\s-]/g,'').replace(/[\s_]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'')}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function imageFile(file,maxW=1600){if(!file||!/^image\/(jpeg|png|webp)$/i.test(file.type))throw Error((file?.name||'Image')+' must be JPG, PNG or WebP.');if(file.size>12*1024*1024)throw Error(file.name+' is larger than 12MB.');const url=URL.createObjectURL(file);try{const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=()=>rej(Error('Cannot decode '+file.name));i.src=url});let w=img.naturalWidth,h=img.naturalHeight;if(w>maxW){const s=maxW/w;w=Math.round(w*s);h=Math.round(h*s)}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);let blob=await new Promise((res,rej)=>c.toBlob(x=>x?res(x):rej(Error('Conversion failed')),'image/webp',.82));if(blob.size>7*1024*1024)blob=await new Promise((res,rej)=>c.toBlob(x=>x?res(x):rej(Error('Compression failed')),'image/webp',.62));if(blob.size>7*1024*1024)throw Error(file.name+' remains larger than 7MB.');return new File([blob],file.name.replace(/\.[^.]+$/,'')+'.webp',{type:'image/webp'})}finally{URL.revokeObjectURL(url)}}
async function uploadBytes(path,file){const buf=new Uint8Array(await file.arrayBuffer());const encoded=path.split('/').map(encodeURIComponent).join('/');let sha;try{const old=await gh('/contents/'+encoded+'?ref='+encodeURIComponent(branch));sha=old?.sha||undefined}catch(e){if(!String(e.message).includes('GitHub 404'))throw e}const payload={message:'Upload '+path,content:b64(buf),branch};if(sha)payload.sha=sha;const r=await gh('/contents/'+encoded,{method:'PUT',body:JSON.stringify(payload)});return r.content.path}
async function deleteFile(path,sha){await gh('/contents/'+path.split('/').map(encodeURIComponent).join('/'),{method:'DELETE',body:JSON.stringify({message:'Delete '+path,sha,branch})})}
async function deleteDir(path){let list;try{list=await gh('/contents/'+path.split('/').map(encodeURIComponent).join('/')+'?ref='+branch)}catch(e){if(String(e.message).includes('404'))return;throw e}for(const f of (Array.isArray(list)?list:[])){if(f.type==='file')await deleteFile(f.path,f.sha);else if(f.type==='dir')await deleteDir(f.path)}}
function render(){const mangas=db.mangas||[],chapters=db.chapters||[];$('stats').innerHTML=`<div><b>${mangas.length}</b><span>Manga</span></div><div><b>${chapters.length}</b><span>Chapters</span></div><div><b>${chapters.reduce((n,c)=>n+(c.pages?.length||0),0)}</b><span>Registered pages</span></div>`;$('cManga').innerHTML=mangas.map(m=>`<option value="${esc(m.id)}">${esc(m.title)} · ${esc(m.country||'')}</option>`).join('');$('mangaList').innerHTML=mangas.map(m=>`<div class="item"><div><b>${esc(m.title)}</b><small>${esc(m.native_title||'')} · ${esc(m.country||'')} · ${esc(m.slug)}</small></div><div><button class="secondary" onclick="editManga('${esc(m.id)}')">Edit</button> <button class="danger" onclick="removeManga('${esc(m.id)}')">Delete</button></div></div>`).join('')||'<p class="muted">No manga yet — clean database.</p>';$('chapterList').innerHTML=chapters.slice().sort((a,b)=>Number(b.number)-Number(a.number)).map(c=>{const m=mangas.find(x=>x.id===c.mangaId)||{};return `<div class="item"><div><b>${esc(m.title||'Unknown')}</b> · Chapter ${esc(c.number)}<small>${esc(c.slug)} · ${(c.pages||[]).length} pages</small></div><div><button onclick="selectChapter('${esc(c.id)}')">Images</button><button class="secondary" onclick="editChapter('${esc(c.id)}')">Edit</button><button class="danger" onclick="removeChapter('${esc(c.id)}')">Delete</button></div></div>`}).join('')||'<p class="muted">No chapters yet.</p>'}
function resetManga(){editMangaId=null;$('saveManga').textContent='Add manga';['mTitle','mNative','mSlug','mLanguage','mAuthor','mArtist','mPublisher','mMagazine','mRelease','mOfficial','mDescription','mGenres'].forEach(id=>$(id).value='');$('mCountry').value='JP';$('mStatus').value='Ongoing';$('mCover').value=''}
window.editManga=id=>{const m=db.mangas.find(x=>x.id===id);if(!m)return;editMangaId=id;$('saveManga').textContent='Update manga';$('mTitle').value=m.title||'';$('mNative').value=m.native_title||'';$('mSlug').value=m.slug||'';$('mCountry').value=m.country||'JP';$('mLanguage').value=m.language||'';$('mStatus').value=m.status||'Ongoing';$('mAuthor').value=m.author||'';$('mArtist').value=m.artist||'';$('mPublisher').value=m.publisher||'';$('mMagazine').value=m.magazine||'';$('mRelease').value=m.release_date||'';$('mOfficial').value=m.official_url||'';$('mDescription').value=m.description||'';$('mGenres').value=(m.genres||[]).join(', ');window.scrollTo({top:0,behavior:'smooth'})};
window.removeManga=async id=>{if(!confirm('Delete this manga, its chapters and registered chapter images?'))return;try{const latest=await readDb(),m=latest.data.mangas.find(x=>x.id===id);if(!m)return;for(const c of latest.data.chapters.filter(c=>c.mangaId===id))await deleteDir(`chapter-images/${m.id}/chapter-${c.number}`);await deleteDir(`manga-covers/${m.slug}`);latest.data.chapters=latest.data.chapters.filter(c=>c.mangaId!==id);latest.data.mangas=latest.data.mangas.filter(x=>x.id!==id);await writeDb(latest.data,latest.sha,'Delete manga and chapters');db=latest.data;await rebuildSitemap();render();msg('✓ Manga and related chapters removed.')}catch(e){msg('Error: '+e.message)}};
$('saveManga').onclick=async()=>{try{const title=$('mTitle').value.trim(),slug=slugify($('mSlug').value||title);if(!title||!slug)throw Error('Title and slug are required.');const latest=await readDb();if(latest.data.mangas.some(x=>x.id!==editMangaId&&x.slug===slug))throw Error('Slug already exists.');let m;if(editMangaId){m=latest.data.mangas.find(x=>x.id===editMangaId);if(!m)throw Error('Manga not found.');const oldCover=m.cover||'';Object.assign(m,{title,native_title:$('mNative').value.trim(),slug,country:$('mCountry').value,language:$('mLanguage').value.trim(),status:$('mStatus').value,author:$('mAuthor').value.trim(),artist:$('mArtist').value.trim(),publisher:$('mPublisher').value.trim(),magazine:$('mMagazine').value.trim(),release_date:$('mRelease').value,official_url:$('mOfficial').value.trim(),description:$('mDescription').value.trim(),genres:$('mGenres').value.split(',').map(x=>x.trim()).filter(Boolean),cover:oldCover})}else{m={id:slug,title,native_title:$('mNative').value.trim(),slug,country:$('mCountry').value,language:$('mLanguage').value.trim(),status:$('mStatus').value,author:$('mAuthor').value.trim(),artist:$('mArtist').value.trim(),publisher:$('mPublisher').value.trim(),magazine:$('mMagazine').value.trim(),release_date:$('mRelease').value,official_url:$('mOfficial').value.trim(),description:$('mDescription').value.trim(),genres:$('mGenres').value.split(',').map(x=>x.trim()).filter(Boolean),cover:'',createdAt:new Date().toISOString()};latest.data.mangas.push(m);editMangaId=m.id}const cover=$('mCover').files[0];if(cover){const f=await imageFile(cover,1200);m.cover=await uploadBytes(`manga-covers/${slug}/cover.webp`,f)}await writeDb(latest.data,latest.sha,editMangaId?'Update manga':'Add manga');db=latest.data;await rebuildSitemap();render();msg('✓ Manga saved.');resetManga()}catch(e){msg('Error: '+e.message)}};
window.editChapter=id=>{const c=db.chapters.find(x=>x.id===id);if(!c)return;editChapterId=id;$('saveChapter').textContent='Update chapter';$('cManga').value=c.mangaId;$('cNumber').value=c.number;$('cTitle').value=c.title||'';$('cSlug').value=c.slug||'';$('cCountry').value=c.country||'JP';$('uploadPanel').classList.remove('hidden');$('selectedChapter').textContent=`Editing: ${c.slug} · ${(c.pages||[]).length} registered pages`;window.scrollTo({top:$('uploadPanel').offsetTop-30,behavior:'smooth'})};
window.selectChapter=id=>{const c=db.chapters.find(x=>x.id===id);if(!c)return;editChapterId=id;$('uploadPanel').classList.remove('hidden');$('selectedChapter').textContent=`Selected: ${c.slug} · ${(c.pages||[]).length} registered pages`;$('cManga').value=c.mangaId};
window.removeChapter=async id=>{if(!confirm('Delete this chapter and all its images?'))return;try{const latest=await readDb(),c=latest.data.chapters.find(x=>x.id===id);if(!c)return;await deleteDir(`chapter-images/${c.mangaId}/chapter-${c.number}`);latest.data.chapters=latest.data.chapters.filter(x=>x.id!==id);await writeDb(latest.data,latest.sha,'Delete chapter');db=latest.data;editChapterId=null;await rebuildSitemap();render();$('uploadPanel').classList.add('hidden');msg('✓ Chapter deleted with images.')}catch(e){msg('Error: '+e.message)}};
$('saveChapter').onclick=async()=>{try{const mangaId=$('cManga').value,number=Number($('cNumber').value),title=$('cTitle').value.trim(),slug=slugify($('cSlug').value);if(!mangaId||!Number.isFinite(number)||!slug)throw Error('Manga, chapter number and slug are required.');const latest=await readDb();if(latest.data.chapters.some(x=>x.id!==editChapterId&&x.slug===slug))throw Error('Slug already exists.');if(editChapterId){const c=latest.data.chapters.find(x=>x.id===editChapterId);if(!c)throw Error('Chapter not found.');Object.assign(c,{mangaId,number,title,slug,country:$('cCountry').value,updatedAt:new Date().toISOString()})}else{latest.data.chapters.push({id:slug,mangaId,number,title,slug,country:$('cCountry').value,pages:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});editChapterId=slug}await writeDb(latest.data,latest.sha,'Save chapter');db=latest.data;await rebuildSitemap();render();selectChapter(editChapterId);msg('✓ Chapter saved. Ab images upload kar sakte ho.')}catch(e){msg('Error: '+e.message)}};
function pageNo(name,fallback,min,max){const m=String(name).match(/(?:page[-_ ]?)?(\d{1,3})(?=\.[^.]+$)/i),n=m?Number(m[1]):fallback;return n>=min&&n<=max?n:fallback}
async function uploadPart(which){const input=$(which===1?'pages1':'pages2'),out=$(which===1?'progress1':'progress2'),files=[...input.files];try{if(!editChapterId)throw Error('Select/save a chapter first.');if(!files.length)throw Error('Select images first.');if(files.length>10)throw Error('Maximum 10 images per part.');const latest=await readDb(),c=latest.data.chapters.find(x=>x.id===editChapterId);if(!c)throw Error('Chapter not found.');const min=which===1?1:11,max=which===1?10:20;let pages=[...(c.pages||[])];for(let i=0;i<files.length;i++){out.textContent+=`Preparing ${i+1}/${files.length}…\n`;const f=await imageFile(files[i]);const n=pageNo(files[i].name,min+i,min,max);const path=`chapter-images/${c.mangaId}/chapter-${c.number}/page-${String(n).padStart(3,'0')}.webp`;await uploadBytes(path,f);pages[n-1]=path;out.textContent+=`✓ page ${n}\n`}c.pages=pages.filter(Boolean).sort((a,b)=>Number((a.match(/page-(\d+)/)||[])[1]||0)-Number((b.match(/page-(\d+)/)||[])[1]||0));c.updatedAt=new Date().toISOString();await writeDb(latest.data,latest.sha,`Upload chapter ${c.number} part ${which}`);db=latest.data;render();$('selectedChapter').textContent=`Selected: ${c.slug} · ${c.pages.length} registered pages`;out.textContent+='\n✓ Part uploaded.';msg('✓ Chapter images saved to GitHub.')}catch(e){out.textContent+='\nERROR: '+e.message;msg('Error: '+e.message)}}
$('upload1').onclick=()=>uploadPart(1);$('upload2').onclick=()=>uploadPart(2);$('clearImages').onclick=async()=>{if(!editChapterId)return msg('Select a chapter first.');if(!confirm('Delete all images for this chapter?'))return;try{const latest=await readDb(),c=latest.data.chapters.find(x=>x.id===editChapterId);await deleteDir(`chapter-images/${c.mangaId}/chapter-${c.number}`);c.pages=[];await writeDb(latest.data,latest.sha,'Clear chapter images');db=latest.data;render();$('selectedChapter').textContent=`Selected: ${c.slug} · 0 registered pages`;msg('✓ All chapter images deleted.')}catch(e){msg('Error: '+e.message)}};
$('resetManga').onclick=resetManga;$('resetChapter').onclick=()=>{editChapterId=null;$('saveChapter').textContent='Add chapter';$('cNumber').value='';$('cTitle').value='';$('cSlug').value='';$('uploadPanel').classList.add('hidden')};
async function rebuildSitemap(){const base=location.origin,urls=[base+'/'];for(const m of db?.mangas||[])urls.push(base+'/manga.html?slug='+encodeURIComponent(m.slug));for(const c of db?.chapters||[])urls.push(base+'/chapter.html?slug='+encodeURIComponent(c.slug));const body='<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(u=>`<url><loc>${esc(u)}</loc></url>`).join('')+'</urlset>\n';try{const old=await gh('/contents/sitemap.xml?ref='+branch);await gh('/contents/sitemap.xml',{method:'PUT',body:JSON.stringify({message:'Update sitemap',content:b64(new TextEncoder().encode(body)),sha:old.sha,branch})})}catch(e){msg('Sitemap update warning: '+e.message)}}
async function load(){db=(await readDb()).data;render()}
$('connect').onclick=async()=>{try{token=$('token').value.trim();owner=$('owner').value.trim();repo=$('repo').value.trim();if(!token||!owner||!repo)throw Error('Token, owner and repository are required.');const me=await fetch('https://api.github.com/user',{headers:ghHeaders()});if(!me.ok)throw Error('Token rejected by GitHub.');await load();sessionStorage.setItem('mangaatlas_token',token);$('login').classList.add('hidden');$('app').classList.remove('hidden');$('repoLabel').textContent=owner+'/'+repo;msg('✓ Connected. Database loaded.')}catch(e){msg('Error: '+e.message,true)}};
$('refresh').onclick=async()=>{try{await load();msg('✓ Refreshed.')}catch(e){msg('Error: '+e.message)}};$('logout').onclick=()=>{sessionStorage.removeItem('mangaatlas_token');location.reload()};if(token){$('token').value=token;$('connect').click()}
